# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
