# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_auto_20171002_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='description',
            field=models.TextField(),
        ),
    ]
