# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0007_auto_20171002_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set([('name', 'state')]),
        ),
        migrations.AlterUniqueTogether(
            name='touristspot',
            unique_together=set([('name', 'city')]),
        ),
    ]
